
export const productList = [
    {
        id: 1,
        title:'Air Force 1 X UNDEFEATED',
        price: 25499,
        image: 'af1xundefeat.jpg',
        stock: 10,
        description: 'asdasdasddasd',
    },
    {
        id:2,
        title:'Air Force 1 07',
        price: 35499,
        image: 'airforce107.jpg',
        stock: 25, 
        description: 'asdasdasddasd',
    },
    {
        id:3,
       title:'Air Max 90 NRG',
        price: 20999,
        image: 'airmax90.jpg',
        stock: 30,
        description: 'Si sos un runner experimentado o estas iniciando las zapatillas Nike Air Max 90 Recycled Canvas Pack son perfectas para ti, estas fueron rediseñadas manteniendo la fidelidad y el respeto a esa silueta para el running hecha en los 90s. Su suela está hecha de goma y posee la unidad Max Air, lo que permite pisadas suaves, amortiguados y saltos altos con una excelente tracción sin importar la superficie.',
    },
    {
        id:4,
        title:'Nike Dunk HI 1985',
        price: 35000,
        image: 'dunkhi.jpg',
        stock: 10,
        description: 'asdasdasddasd',
    },
    {
        id:5,
        title:'Nike Dunk Low SE',
        price: 29999,
        image: 'dunklow.jpg',
        stock: 20,
        description: 'asdasdasddasd',
    },
    {
        id:6,
        title:'Air Jordan 5 Retro ORANGE BLAZE',
        price: 25499,
        image: 'jordanorangeblaze1.jpg',
        stock: 17,
        description: 'asdasdasddasd',
    },
    {
        id: 7,
        title:'Air Jordan 1 High SEAFOAM',
        price: 20000,
        image: 'jordan1seafoam.jpg',
        stock: 20,
        description: 'asdasdasddasd',
    },
    {
        id: 8,
        title:'Nike LDWaffle x Sacai',
        price: 50000,
        image: 'ldwaffle.jpg',
        stock: 20,
        description: 'asdasdasddasd',
    },
];